(() => {
  const $=s=>document.querySelector(s),el=(tag,content,cls)=>{const n=document.createElement(tag);if(content!=null)n.textContent=content;if(cls)n.className=cls;return n;};
  const api=String(window.FIONA_APP_CONFIG.gallery?.apiBase||'').replace(/\/$/,'');
  const seed={id:'medal',url:'./assets/fiona-portrait.jpg',title:'Fiona mit ihrer Goldmedaille',caption:'Ein persönlicher Moment.',album:'Momente',date:'',local:true};
  let photos=[seed],cursor=null,album='Alle',key='',loaded=false,busy=false,active=0;
  const notify=message=>{$('#galleryMessage').textContent=message;};
  async function request(path,options={}){const response=await fetch(api+path,{...options,cache:'no-store',signal:AbortSignal.timeout(30000)});const data=await response.json();if(response.status===404&&options.method==='POST'&&path.startsWith('/photos/'))throw Error('Zum Bearbeiten bitte den aktualisierten Galerie-Code in Cloudflare bereitstellen.');if(!response.ok)throw Error(data.error||'Anfrage fehlgeschlagen.');return data;}
  const visible=()=>photos.filter(p=>album==='Alle'||p.album===album);
  function open(index){const list=visible();if(!list.length)return;active=(index+list.length)%list.length;const photo=list[active],dialog=$('#resultDetail'),root=$('#detailContent');root.classList.remove('team-result-detail');root.replaceChildren();const image=el('img',null,'gallery-large');image.src=photo.url;image.alt=photo.title||'Fionas Fotogalerie';root.append(el('h2',photo.title||'Fionas Moment'),image);const nav=el('div',null,'gallery-lightbox-nav');for(const [label,delta] of [['← Voriges',-1],['Nächstes →',1]]){const b=el('button',label,'tab');b.onclick=()=>open(active+delta);nav.append(b);}nav.append(el('span',(active+1)+' / '+list.length));const shareButton=el('button','Foto teilen · WhatsApp','tab');shareButton.onclick=()=>share(photo);root.append(shareButton);root.append(nav,el('p',[photo.album,photo.date].filter(Boolean).join(' · '),'card-sub'),el('p',photo.caption||'','gallery-caption'));
    let x;image.onpointerdown=e=>{x=e.clientX;};image.onpointerup=e=>{if(x!=null&&Math.abs(e.clientX-x)>40)open(active+(e.clientX<x?1:-1));x=null;};
    dialog.onkeydown=e=>{if(e.key==='ArrowRight'){e.preventDefault();open(active+1);}if(e.key==='ArrowLeft'){e.preventDefault();open(active-1);}};$('#closeDetail').onclick=()=>dialog.close();if(!dialog.open)dialog.showModal();
  }
  async function share(photo){
    const url=new URL(photo.url,location.href).href,title=photo.title||'Fiona Matt Athletics';
    try{
      if(navigator.share){
        if(navigator.canShare){try{const response=await fetch(url);if(!response.ok)throw Error('Foto nicht erreichbar');const blob=await response.blob(),file=new File([blob],'fiona-foto.'+(blob.type==='image/png'?'png':blob.type==='image/webp'?'webp':'jpg'),{type:blob.type});if(navigator.canShare({files:[file]})){await navigator.share({title,text:photo.caption||title,files:[file]});return;}}catch(e){if(e.name==='AbortError')return;}}
        await navigator.share({title,text:photo.caption||title,url});return;
      }
      window.open('https://wa.me/?text='+encodeURIComponent(title+'\n'+url),'_blank','noopener,noreferrer');
    }catch(e){if(e.name!=='AbortError')notify('Teilen nicht möglich. Bitte erneut versuchen.');}
  }
  function edit(photo){
    const dialog=$('#resultDetail'),root=$('#detailContent');root.classList.remove('team-result-detail');root.replaceChildren(el('h2','Foto beschriften'));const form=el('form',null,'gallery-form');
    const values={};for(const [name,label,type,max] of [['title','Titel','text',100],['caption','Beschreibung','textarea',300],['album','Album','text',40],['date','Aufnahmedatum','date',10]]){const wrap=el('label',label),input=el(type==='textarea'?'textarea':'input');if(type!=='textarea')input.type=type;input.name=name;input.maxLength=max;input.value=photo[name]||'';wrap.append(input);form.append(wrap);values[name]=input;}
    const message=el('p','','data-note');message.setAttribute('role','status');const save=el('button','Speichern','tab');save.type='submit';const cancel=el('button','Abbrechen','tab');cancel.type='button';cancel.onclick=()=>dialog.close();form.append(message,save,cancel);root.append(form);
    form.onsubmit=async e=>{e.preventDefault();save.disabled=true;try{const data=await request('/photos/'+encodeURIComponent(photo.id),{method:'POST',headers:{Authorization:'Bearer '+key,'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(Object.entries(values).map(([name,input])=>[name,input.value])))});Object.assign(photo,data.photo);if(album!=='Alle'&&!photos.some(p=>p.album===album))album='Alle';render();dialog.close();notify('Beschriftung gespeichert.');}catch(err){message.textContent=err.message;}finally{save.disabled=false;}};
    $('#closeDetail').onclick=()=>dialog.close();if(!dialog.open)dialog.showModal();
  }
  function render(){const filters=$('#galleryAlbums');filters.replaceChildren();for(const name of ['Alle',...new Set(photos.map(p=>p.album))]){const b=el('button',name,'tab'+(album===name?' active':''));b.onclick=()=>{album=name;render();};filters.append(b);}const grid=$('#galleryGrid');grid.replaceChildren();visible().forEach((photo,index)=>{const card=el('article',null,'gallery-photo'),b=el('button',null,'gallery-photo-open'),img=el('img');b.type='button';b.setAttribute('aria-label',(photo.title||'Foto')+' vergrössern');img.src=photo.url;img.alt=photo.title||'Foto von Fiona';img.loading='lazy';b.append(img,el('strong',photo.title||'Ein Moment'),el('span',[photo.album,photo.date].filter(Boolean).join(' · ')));b.onclick=()=>open(index);card.append(b);const actions=el('div',null,'gallery-actions'),shareButton=el('button','Teilen','gallery-action');shareButton.onclick=()=>share(photo);actions.append(shareButton);card.append(actions);if(key&&!photo.local){const editButton=el('button','Bearbeiten','gallery-action');editButton.onclick=()=>edit(photo);actions.append(editButton);const remove=el('button','Foto löschen','gallery-delete');remove.onclick=()=>{remove.textContent='Endgültig löschen?';remove.onclick=async()=>{remove.disabled=true;try{await request('/photos/'+encodeURIComponent(photo.id),{method:'DELETE',headers:{Authorization:'Bearer '+key}});photos=photos.filter(p=>p.id!==photo.id);render();notify('Foto gelöscht.');}catch(e){notify(e.message);remove.disabled=false;}};};actions.append(remove);}grid.append(card);});$('#galleryMore').hidden=!cursor;$('#galleryUploadForm').hidden=!key;$('#galleryLoginForm').hidden=!!key;$('#galleryLogout').hidden=!key;}
  async function load(more=false){if(!api){notify('Die Galerie startet mit Fionas Medaillenfoto. Der Handy-Upload wird nach der Speicheranbindung freigeschaltet.');return;}try{const data=await request('/photos'+(more&&cursor?'?cursor='+encodeURIComponent(cursor):''));if(!Array.isArray(data.photos))throw Error('Fotoliste nicht verfügbar.');const safe=data.photos.filter(p=>{try{const u=new URL(p.url);return u.origin===new URL(api).origin&&u.pathname.startsWith('/photos/');}catch{return false;}});photos=more?[...photos,...safe.filter(p=>!photos.some(x=>x.id===p.id))]:[seed,...safe];cursor=data.cursor;loaded=true;render();notify('');}catch(e){notify('Fotos momentan nicht erreichbar. '+e.message);}}
  async function compress(file){if(file.size>40*1024*1024)throw Error(file.name+': Datei zu gross.');if(!/^image\/(jpeg|png|webp|heic|heif)$/.test(file.type))throw Error(file.name+': Bitte JPEG, PNG oder WebP wählen.');const url=URL.createObjectURL(file);try{const img=new Image();await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=()=>reject(Error(file.name+': Format kann auf diesem Gerät nicht geöffnet werden. Bitte als JPEG exportieren.'));img.src=url;});const factor=Math.min(1,2048/Math.max(img.naturalWidth,img.naturalHeight)),canvas=document.createElement('canvas');canvas.width=Math.round(img.naturalWidth*factor);canvas.height=Math.round(img.naturalHeight*factor);const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.86));if(!blob||blob.size>8*1024*1024)throw Error(file.name+': Verkleinerung fehlgeschlagen.');return blob;}finally{URL.revokeObjectURL(url);}}
  $('#galleryManage').onclick=()=>{$('#galleryManagement').hidden=!$('#galleryManagement').hidden;};
  $('#galleryLoginForm').onsubmit=async e=>{e.preventDefault();if(!api){notify('Upload noch nicht freigeschaltet.');return;}const input=$('#galleryKey'),value=input.value;try{const data=await request('/auth',{method:'POST',headers:{Authorization:'Bearer '+value}});key=value;input.value='';render();notify('Angemeldet als '+data.name+'.');}catch(err){input.value='';notify(err.message);}};
  $('#galleryLogout').onclick=()=>{key='';render();notify('Abgemeldet.');};
  $('#galleryUploadForm').onsubmit=async e=>{e.preventDefault();if(!key||busy)return;const files=[...$('#galleryFiles').files];if(!files.length){notify('Bitte Fotos auswählen.');return;}if(files.length>20){notify('Bitte höchstens 20 Fotos auf einmal auswählen.');return;}busy=true;const button=$('#gallerySend');button.disabled=true;let count=0;try{for(const file of files){notify('Foto '+(count+1)+' von '+files.length+' wird vorbereitet …');const blob=await compress(file),params=new URLSearchParams({album:$('#galleryAlbum').value,title:$('#galleryTitle').value,caption:$('#galleryCaption').value,date:$('#galleryDate').value});await request('/photos?'+params,{method:'POST',headers:{Authorization:'Bearer '+key,'Content-Type':'image/jpeg'},body:blob});count++;}$('#galleryFiles').value='';await load();notify(count+' Foto(s) veröffentlicht.');}catch(err){if(count)await load();notify(count+' Foto(s) veröffentlicht. '+err.message+' Bereits hochgeladene Fotos bleiben erhalten.');}finally{busy=false;button.disabled=false;}};
  $('#resultDetail').addEventListener('close',()=>{$('#resultDetail').onkeydown=null;});
  $('#galleryMore').onclick=()=>load(true);$('#galleryRefresh').onclick=()=>load();window.addEventListener('fiona-view',e=>{if(e.detail.view==='gallery'&&!loaded)load();});render();if($('#view-gallery').classList.contains('active'))load();
})();
