(() => {
 const $=s=>document.querySelector(s),node=(tag,label)=>{const e=document.createElement(tag);if(label)e.textContent=label;return e;},api=window.FIONA_APP_CONFIG.gallery?.apiBase,original='./assets/fiona-portrait.jpg';
 let current=null;
 async function read(path){const r=await fetch(api+path,{cache:'no-store',signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error(r.status===404?'Bitte den aktuellen Galerie-Code in Cloudflare bereitstellen.':'Fotos momentan nicht erreichbar.');return r.json();}
 function apply(data){if(!data?.url)return;const u=new URL(data.url);if(u.origin!==new URL(api).origin||u.pathname!='/profile/image')return;current=data;for(const img of document.querySelectorAll('#openPortrait img,.topbar-portrait')){img.src=data.url;img.alt='Fiona Matt';img.style.objectPosition=data.x+'% '+data.y+'%';img.onerror=()=>{img.onerror=null;img.src=original;img.style.objectPosition='';};}}
 const originalZoom=$('#openPortrait').onclick;$('#openPortrait').onclick=()=>{originalZoom();if(current){const img=$('#detailContent img');img.src=current.url;img.alt='Fionas Profilfoto';}};
 // The medal milestone always retains its historic original photograph.
 $('#openMedalMoment').onclick=originalZoom;
 $('#changeProfilePhoto').onclick=()=>{
  const dialog=$('#resultDetail'),root=$('#detailContent');root.classList.remove('team-result-detail');root.replaceChildren(node('h2','Profilfoto ändern'));
  const form=node('form');form.className='gallery-form profile-form';const status=node('p');status.className='data-note profile-status';status.setAttribute('role','status');
  const label=node('label','Upload-Code'),secret=node('input');secret.type='password';secret.autocomplete='off';label.append(secret);label.hidden=window.FionaGallery.hasAccess();form.append(label);
  const hint=node('p','Das Profilfoto ist öffentlich. Du kannst ein Handyfoto oder ein Bild aus der Galerie wählen.');hint.className='data-note';form.append(hint);
  const fileLabel=node('label','Foto vom Handy auswählen'),file=node('input');file.type='file';file.accept='image/jpeg,image/png,image/webp,image/heic,image/heif';fileLabel.append(file);form.append(fileLabel);
  const choose=node('button','Aus Galerie auswählen');choose.type='button';choose.className='tab';const picks=node('div');picks.className='profile-picks';picks.hidden=true;form.append(choose,picks);
  const image=node('img');image.className='profile-preview';image.alt='Vorschau des Bildausschnitts';image.src=current?.url||original;form.append(image);
  let selected=null,blob=null,previewURL=null,cursor=null;
  const controls={};for(const [name,title,value] of [['x','Ausschnitt links / rechts',current?.x??50],['y','Ausschnitt oben / unten',current?.y??32]]){const wrap=node('label',title),input=node('input');input.type='range';input.min=0;input.max=100;input.value=value;input.name=name;wrap.append(input);form.append(wrap);controls[name]=input;input.oninput=()=>image.style.objectPosition=controls.x.value+'% '+controls.y.value+'%';}controls.x.oninput();
  const save=node('button','Profilfoto speichern');save.type='submit';save.className='tab';save.disabled=true;const cancel=node('button','Abbrechen');cancel.type='button';cancel.className='tab';cancel.onclick=()=>dialog.close();form.append(status,save,cancel);root.append(form);
  file.onchange=async()=>{save.disabled=true;try{if(!file.files[0])return;blob=await window.FionaGallery.compress(file.files[0]);selected=null;if(previewURL)URL.revokeObjectURL(previewURL);previewURL=URL.createObjectURL(blob);image.src=previewURL;save.disabled=false;status.textContent='Ausschnitt einstellen und speichern.';}catch(e){status.textContent=e.message;}};
  choose.onclick=async()=>{choose.disabled=true;try{const data=await read('/photos'+(cursor?'?cursor='+encodeURIComponent(cursor):''));picks.hidden=false;for(const photo of data.photos){const u=new URL(photo.url);if(u.origin!==new URL(api).origin||!u.pathname.startsWith('/photos/'))continue;const button=node('button'),thumb=node('img');button.type='button';button.setAttribute('aria-label',photo.title||'Galeriefoto auswählen');thumb.src=photo.url;thumb.alt=photo.title||'Galeriefoto';button.append(thumb);button.onclick=()=>{selected=photo;blob=null;image.src=photo.url;save.disabled=false;status.textContent='Ausschnitt einstellen und speichern.';};picks.append(button);}cursor=data.cursor;choose.textContent=cursor?'Weitere Galeriefotos laden':'Galerie geladen';choose.hidden=!cursor;}catch(e){status.textContent=e.message;}finally{choose.disabled=false;}};
  form.onsubmit=async e=>{e.preventDefault();save.disabled=true;file.disabled=true;choose.disabled=true;try{if(!window.FionaGallery.hasAccess()){const value=secret.value;secret.value='';await window.FionaGallery.authenticate(value);label.hidden=true;}await read('/profile');if(blob&&!selected){const data=await window.FionaGallery.write('/photos?album=Profilfotos&title=Fiona%20Matt',{method:'POST',headers:{'Content-Type':'image/jpeg'},body:blob});selected=data.photo;}if(!selected)throw Error('Bitte zuerst ein Foto auswählen.');const data=await window.FionaGallery.write('/profile',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:selected.id,x:Number(controls.x.value),y:Number(controls.y.value)})});apply(data);dialog.close();$('#galleryRefresh').click();}catch(e){status.textContent=e.message;}finally{save.disabled=false;file.disabled=false;choose.disabled=false;}};
  const cleanup=()=>{if(previewURL)URL.revokeObjectURL(previewURL);secret.value='';};dialog.addEventListener('close',cleanup,{once:true});$('#closeDetail').onclick=()=>dialog.close();dialog.showModal();
 };
 if(api)read('/profile').then(apply).catch(()=>{});
})();
