const test=require('node:test');const assert=require('node:assert/strict');const M=require('../data-models.js');
test('Dates from Swiss Athletics, WA and historical monthly labels retain chronology',()=>{assert.equal(M.dateKey('21.02.2026'),'2026-02-21');assert.equal(M.dateKey('09 MAY 2026'),'2026-05-09');assert.equal(M.dateKey("Feb '26d"),'2026-02-01');assert.equal(M.dateKey('31.02.2026'),'');assert.equal(M.dateKey('bad date'),'');});
test('Equal WA scores in different months must not erase history',()=>{const rows=M.scoreRows([{discipline:'100 Metres',date:'09 MAY 2026',score:986,result:'12.03'}],[{label:"Apr '25",val:879},{label:"Sep '24",val:879},{label:"Mai '26",val:986}],'100m');assert.equal(rows.length,3);assert.deepEqual(rows.map(r=>r.dateISO),['2024-09-01','2025-04-01','2026-05-09']);});
test('2026 live ranking never overwrites frozen 2025 results or invents adjacent gaps',()=>{const historical={club:'TV Eschen-Mauren',rankingData:{'100m':{'2025':{rank:18,result:'12.24'}}},top10Static:{'100m':{'2025':[{rank:1,name:'A',result:'11.24'}]}}};const live={disciplines:{'100m':{year:'2026',top15:[{rank:1,name:'B',result:'11.90'}],fiona:{rank:2,result:'12.03'}}}};assert.equal(M.ranking(live,historical,'100m','2025').fiona.result,'12.24');assert.equal(M.ranking(live,historical,'100m','2025').gapAhead,null);assert.equal(M.ranking(live,historical,'100m','2026').gapAhead,'0.13');});
test('Training preserves the fullest duplicate comment and excludes competitions',()=>{const entries=[{id:1,name:'Max Velocity',date:'03.10.2026',comment:'Short'},{id:2,name:'Max Velocity',date:'03.10.2026',comment:'Full details: 5 x fly 20m'},{id:3,name:'WK: Meeting',date:'04.10.2026'},{id:4,name:'Strength',date:'05.10.2026',isWettkampf:false}];const out=M.trainingEvents(entries);assert.deepEqual(out.map(e=>e.id),[2,4]);assert.equal(M.isCompetition({name:'WK: Sprint',isWettkampf:false}),false);});
test('Result normalization keeps laportal enrichment and numeric years interoperable',()=>{const r=M.normalizeResults({results:[{discipline:'100 Metres',result:'12,03',date:'09.05.2026',top5:[{name:'A'}],fionaRank:3,wind:'1,0'}]}).results[0];assert.equal(r.numResult,12.03);assert.equal(r.dateISO,'2026-05-09');assert.equal(r.discipline,'100m');assert.equal(r.top5[0].name,'A');assert.equal(r.fionaRank,3);});
test('Actual WA object response keeps July results, performance and wind',()=>{const payload=require('./fixtures/wa-results.json');const rows=M.scoreRows(payload,[],'100m');assert.equal(rows.at(-1).dateISO,'2026-07-01');assert.equal(rows.at(-1).result,'11.91');assert.equal(rows.at(-1).wind,'+1.7');assert.equal(rows.at(-1).score,1009);assert.equal(M.scoreRows(payload.results,[],'100m').length,rows.length);});
test('Team ranks top two disciplines across athletes, preserves ties and unscored entries',()=>{const data={A:{discs:[{name:'100m',score:900},{name:'60m',score:1000},{name:'200m',score:800}]},B:{discs:[{name:'Speer',score:1000},{name:'Hoch',score:920}]},C:{discs:[{name:'Speer',score:0}]}};const rows=M.teamRanking(data,[{name:'A',gender:'f'},{name:'B',gender:'m'},{name:'C'},{name:'Missing'}]);assert.deepEqual(rows.slice(0,4).map(r=>r.score),[1000,1000,920,900]);assert.deepEqual(rows.slice(0,4).map(r=>r.rank),[1,1,3,4]);assert.equal(rows.filter(r=>r.athleteName==='A').length,2);assert.equal(rows.find(r=>r.athleteName==='C').rank,null);assert.equal(rows.find(r=>r.athleteName==='Missing').rank,null);assert.equal(M.teamRanking(data,[{name:'A',gender:'f'},{name:'B',gender:'m'}],'f').length,2);});
test('Team context matches exact discipline, mark and score; never uses source update as meet date',()=>{const verling=require('./fixtures/athletes/verling.json');const row={name:'Speer',result:'72.90 NR',score:1000,updated:'25 APR 2026'};const matched=M.matchTeamPerformance(row,verling);assert.equal(matched.date,'25 JUN 2025');assert(matched.venue.includes('Maribor'));assert.equal(M.matchTeamPerformance({...row,result:'72.91'},verling),null);assert.equal(M.matchTeamPerformance({...row,score:999},verling),null);const fiona=require('./fixtures/athletes/fiona.json');const pb=M.matchTeamPerformance({name:'100m',result:'11.82',score:1010},fiona);assert.equal(pb.date,'11 JUL 2026');assert.equal(pb.matchType,'pb');assert.equal(pb.venue,undefined);});

test('Actual latest 100m results retain times and sort heats before final; assisted 11.82 is excluded',()=>{const raw=require('./fixtures/chart-latest.json'),rows=M.chartResults(M.normalizeResults({results:raw}).results,'100m');assert.deepEqual(rows.slice(-3).map(r=>r.result),['12.26','11.96','12.07']);assert.deepEqual(rows.slice(-3).map(r=>r.place),['9h8','3qf4','4f1']);assert(!rows.some(r=>r.result==='11.82'));assert.equal(M.chartResults(rows,'100m','2025').length,0);});

test('Race identifiers are readable without inventing missing rounds or lane numbers',()=>{assert.equal(M.raceLabel('4f1'),'Finale · Rang 4 · Lauf 1');assert.equal(M.raceLabel('9h8'),'Vorlauf · Rang 9 · Lauf 8');assert.equal(M.raceLabel('2sf2'),'Halbfinale · Rang 2 · Lauf 2');assert.equal(M.raceLabel('3qf4'),'Viertelfinale · Rang 3 · Lauf 4');assert.equal(M.raceLabel('1r5'),'Serie · Rang 1 · Lauf 5');assert.equal(M.raceLabel('5. Lauf 3'),'Lauf 3 · Rang 5');assert.equal(M.raceLabel(null),'—');assert.equal(M.raceLabel('DNF'),'DNF');});
test('Result tables show newest dates, fastest first within a day while chart keeps race chronology',()=>{const raw=require('./fixtures/chart-latest.json'),rows=M.normalizeResults({results:raw}).results;assert.deepEqual(M.resultTableRows(M.chartResults(rows,'100m')).slice(0,3).map(r=>r.result),['11.96','12.07','12.26']);assert.deepEqual(M.chartResults(rows,'100m').slice(-3).map(r=>r.result),['12.26','11.96','12.07']);assert.deepEqual(M.resultTableRows([{discipline:'Long Jump',date:'2026-01-01',result:'5.20'},{discipline:'Long Jump',date:'2026-01-01',result:'5.50'}]).map(r=>r.result),['5.50','5.20']);});

test('Ranking birth years use supplied dates and Fiona is recognised in either name order',()=>{assert.equal(M.birthYear('02.09.2009'),'2009');assert.equal(M.birthYear('2008'),'2008');assert.equal(M.birthYear('unknown'),'');assert(M.isFionaName('Matt Fiona'));});
test('Youth implement match requires exact mark and record code, keeping the delivered 700g discipline',()=>{const ben=require('./fixtures/athletes/seger.json');const row={name:'Javelin Throw',result:'58.49 NU18R',score:0};const m=M.matchTeamPerformance(row,ben);assert.equal(m.discipline,'Javelin Throw (700g)');assert.equal(m.date,'17 MAY 2024');assert(m.venue.includes('Schaan'));assert.equal(M.matchTeamPerformance({...row,result:'58.49'},ben),null);assert.equal(M.matchTeamPerformance({...row,result:'58.50 NU18R'},ben),null);});
