const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');const {JSDOM}=require('jsdom');
const scripts=['config.js','historical-data.js','data-models.js','data-adapters.js','app.js','migration-ui.js','extensions.js'];
const fixtures=require('./fixtures');
async function boot({offline=false,saveError=false,failActions=[],seed={}}={}){const dom=new JSDOM(fs.readFileSync('index.html','utf8'),{runScripts:'outside-only',url:'https://example.test/Fiona-Matt/'});const w=dom.window,errors=[],writes=[];w.addEventListener('error',e=>errors.push(e.error));for(const [key,val] of Object.entries(seed))w.localStorage.setItem(key,val);w.scrollTo=()=>{};w.AbortSignal=AbortSignal;w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};w.fetch=async(url,options={})=>{if(String(url).includes('athlete_results.json'))return{ok:true,json:async()=>fixtures['sa-results']};const action=new URL(url).searchParams.get('action');if(options.method==='POST'){writes.push({action,body:JSON.parse(options.body)});return{ok:true,json:async()=>saveError?{ok:false,error:'Write rejected'}:{ok:true}};}if(offline||failActions.includes(action))throw Error('offline');return{ok:true,json:async()=>fixtures[action]};};for(const script of scripts)w.eval(fs.readFileSync(script,'utf8'));await new Promise(r=>setTimeout(r,30));return{dom,w,errors,writes,close:()=>w.close()};}
test('V2 loads all existing sources and opens results, rankings, WA zoom and Team LIE without writes',async()=>{const b=await boot();try{const d=b.w.document;assert.equal(d.querySelectorAll('#allResults .result').length,168);assert.equal(d.querySelectorAll('#sourcePanels .card').length,7);assert(d.querySelector('#teamContent').textContent.includes('Fiona Matt'));assert(d.querySelector('#teamContent').textContent.includes('Julia Rohrer'));assert(d.querySelector('#rankingsContent').textContent.includes('0.13'));d.querySelector('[data-view="results"]').click();d.querySelector('#allResults .result').click();assert(d.querySelector('#resultDetail').open);d.querySelector('#closeDetail').click();[...d.querySelectorAll('#waContent button')].find(b=>b.textContent==='Chart vergrössern').click();assert(d.querySelector('#resultDetail svg'));assert.equal(b.writes.length,0);assert.deepEqual(b.errors,[]);}finally{b.close();}});
test('Calendar edits use the existing API, while a failed save keeps form and displayed records',async()=>{const b=await boot({saveError:true});try{const d=b.w.document;const edit=[...d.querySelectorAll('#calendarContent button')].find(b=>b.textContent==='Bearbeiten');edit.click();const form=d.querySelector('#detailContent form');form.querySelector('input[type=text]').value='Changed meeting';form.dispatchEvent(new b.w.Event('submit',{cancelable:true}));await new Promise(r=>setTimeout(r,30));assert.equal(b.writes[0].action,'calendar-update');assert.equal(b.writes[0].body.id,17);assert.equal(b.writes[0].body.date,'08.11.2026');assert(d.querySelector('#detailContent').textContent.includes('Nicht gespeichert: Write rejected'));assert(d.querySelector('#resultDetail').open);assert(d.querySelector('#calendarContent').textContent.includes('WK: Dakar'));assert.deepEqual(b.errors,[]);}finally{b.close();}});
test('Offline first visit retains 168 local results, frozen 2025 ranks and historical WA chart',async()=>{const b=await boot({offline:true});try{const d=b.w.document;assert.equal(d.querySelectorAll('#allResults .result').length,168);const ui=b.w.FionaMigrationUI;ui.state.rankYear='2025';ui.renderRankings();assert(d.querySelector('#rankingsContent').textContent.includes('12.24'));assert(d.querySelector('#rankingsContent').textContent.includes('Historischer'));assert(d.querySelector('#waContent svg'));assert.equal(b.writes.length,0);assert.deepEqual(b.errors,[]);}finally{b.close();}});
test('Deleting requires an explicit second button; successful writes reload sources without duplicate panels',async()=>{const b=await boot();try{const d=b.w.document;[...d.querySelectorAll('#calendarContent button')].find(b=>b.textContent==='Löschen').click();assert.equal(b.writes.length,0);[...d.querySelectorAll('#detailContent button')].find(b=>b.textContent==='Diesen Wettkampf löschen').click();await new Promise(r=>setTimeout(r,30));assert.deepEqual(b.writes,[{action:'calendar-delete',body:{id:17}}]);assert.equal(d.querySelectorAll('#sourcePanels .card').length,7);assert.equal(d.querySelector('#resultDetail').open,false);assert.deepEqual(b.errors,[]);}finally{b.close();}});

test('One failing source does not block other modules, and cached data stays visibly dated',async()=>{const key='fiona-v2-source:lieteam';const cached={action:'lieteam',title:'Team Liechtenstein',data:fixtures.lieteam,loadedAt:'2026-09-01T10:00:00Z',status:'live'};const b=await boot({failActions:['lieteam'],seed:{[key]:JSON.stringify(cached)}});try{const d=b.w.document;assert(d.querySelector('#teamContent').textContent.includes('Gespeicherter Abruf'));assert(d.querySelector('#teamContent').textContent.includes('Fiona Matt'));assert(d.querySelector('#rankingsContent').textContent.includes('0.13'));assert.equal(d.querySelectorAll('#sourcePanels .card').length,7);assert.deepEqual(b.errors,[]);}finally{b.close();}});
test('Shared view hash and individual athlete data remain usable',async()=>{const b=await boot();try{const d=b.w.document;d.querySelector('[data-goto="team"]').click();assert.equal(b.w.location.hash,'#team');assert(d.querySelector('#view-team').classList.contains('active'));[...d.querySelectorAll('#teamContent button')].find(b=>b.textContent==='Fiona Matt').click();await new Promise(r=>setTimeout(r,30));assert(d.querySelector('#detailContent').textContent.includes('Top 5'));assert(d.querySelector('#detailContent').textContent.includes('12.03'));assert.equal(b.writes.length,0);assert.deepEqual(b.errors,[]);}finally{b.close();}});
